version: '3.8'

services:
  # Flask Application
  flask:
    build: .
    container_name: jobmato-flask-app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - PORT=5003
      - HOST=0.0.0.0
      - REDIS_URL=redis://143.244.135.42
      - REDIS_PASSWORD=SgYEtc6WAOgalgLviUDHFV1Yskt
      - MONGODB_URI=mongodb+srv://doadmin:064CU93w5RlQvz18@db-postgresql-blr1--main-db-009faed0.mongo.ondigitalocean.com
      - MONGODB_DATABASE=admin
      - MONGODB_COLLECTION=chatsessions
      - SECRET_KEY=your-production-secret-key-change-this
      - JWT_SECRET=your-jwt-secret-change-this
    networks:
      - jobmato-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: jobmato-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - flask
    networks:
      - jobmato-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: jobmato-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email jobmatofficial@gmail.com --agree-tos --no-eff-email --staging -d chatbot-server.jobmato.com
    depends_on:
      - nginx
    networks:
      - jobmato-network

networks:
  jobmato-network:
    driver: bridge

volumes:
  certbot-conf:
  certbot-www: 